name: Build and deploy to docker hub

on:
    push:
        branches:
            - main


jobs:
    build-and-push:
        runs-on: ubuntu-latest
        steps:
            - name: Check Out Repo
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v1
              with:
                username: ${{secrets.GITHUB_TOKEN.Docker_Username}}
                password: ${{secrets.GITHUB_TOKEN.Docker_Password}}

            - name: Build and push docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                file: ./docker/Dockerfile.user
                push: true
                tags: rj9041/mynextapp:latest

            - name: Verify Pushed Image
              run: docker pull rj9041/mynextapp:latest